/** @jsx jsx */
import { jsx } from "@emotion/core";

import {
  AppsAndGames,
  Auction,
  BeautyEngagement,
  Bullhorn,
  Leaf,
  Hardhat,
  BrokerServices,
  Cars,
  Clothes,
  Complaint,
  ComputerTvGameConsole,
  ConcertAndEvent,
  ConsumerRights,
  ContractWorkHouses,
  Craftsman,
  DistanceContractLaw,
  EducationAndCourses,
  ElectricityHeatingContract,
  FurnituresAndDecoration,
  GymAndWorkoutService,
  Hairdresser,
  Insurance,
  InternetFiberBroadband,
  LoanSaveInvest,
  LotteryAndGames,
  MobilePhone,
  MoveAndCleaningService,
  NotDefinedPicture,
  Pets,
  PurchaseFromPrivate,
  Receipt,
  SalesLaw,
  Telemarketing,
  Travel,
  WhiteGoods,
  Withdrawal,
  Pen,
  Map,
  ChatWithUs,
  CallUs,
  Mic,
  DatingServices,
  UserInjured,
  BabyCarriage,
  Ellipsis,
  HandHeart,
  Snowboarding,
  DBAnimalsIcon,
  DBCalendarIcon,
  DBCarIcon,
  DBClothesIcon,
  DBDeleteIcon,
  DBEducationIcon,
  DBEnergyIcon,
  DBFaqAnswerIcon,
  DBFaqQuestionIcon,
  DBFoodIcon,
  DBFridgeIcon,
  DBFurnitureIcon,
  DBGamesIcon,
  DBHealthIcon,
  DBJusticeIcon,
  DBLeisureIcon,
  DBMovingIcon,
  DBOnlineGamingIcon,
  DBPadlockIcon,
  DBPhoneIcon,
  DBRenovationIcon,
  DBRentIcon,
  DBTravelIcon,
  DBWarningIcon,
  DBWifiIcon,
  DBSocialShareIcon,
  DBFriendshipIcon,
  DBWebsiteInfoIcon,
  RSS
} from "@konsumentverket-sverige/designsystem.utils";

const editorIconDefinitions = {
  AppsAndGames,
  Auction,
  BeautyEngagement,
  Bullhorn,
  Leaf,
  Hardhat,
  BrokerServices,
  Cars,
  Clothes,
  Complaint,
  ComputerTvGameConsole,
  ConcertAndEvent,
  ConsumerRights,
  ContractWorkHouses,
  Craftsman,
  DistanceContractLaw,
  EducationAndCourses,
  ElectricityHeatingContract,
  FurnituresAndDecoration,
  GymAndWorkoutService,
  Hairdresser,
  Insurance,
  InternetFiberBroadband,
  LoanSaveInvest,
  LotteryAndGames,
  MobilePhone,
  MoveAndCleaningService,
  NotDefinedPicture,
  Pets,
  PurchaseFromPrivate,
  Receipt,
  SalesLaw,
  Telemarketing,
  Travel,
  WhiteGoods,
  Withdrawal,
  Pen,
  Map,
  ChatWithUs,
  CallUs,
  Mic,
  DatingServices,
  UserInjured,
  BabyCarriage,
  Ellipsis,
  HandHeart,
  Snowboarding,
  DBAnimalsIcon,
  DBCalendarIcon,
  DBCarIcon,
  DBClothesIcon,
  DBDeleteIcon,
  DBEducationIcon,
  DBEnergyIcon,
  DBFaqAnswerIcon,
  DBFaqQuestionIcon,
  DBFoodIcon,
  DBFridgeIcon,
  DBFurnitureIcon,
  DBGamesIcon,
  DBHealthIcon,
  DBJusticeIcon,
  DBLeisureIcon,
  DBMovingIcon,
  DBOnlineGamingIcon,
  DBPadlockIcon,
  DBPhoneIcon,
  DBRenovationIcon,
  DBRentIcon,
  DBTravelIcon,
  DBWarningIcon,
  DBWifiIcon,
  DBSocialShareIcon,
  DBFriendshipIcon,
  DBWebsiteInfoIcon,
  RSS
};

const EditorIcon = ({ icon, className, style, title, ...otherAttr }) => {
  const Element = editorIconDefinitions[icon];

  if (Element === undefined) {
    return null;
  }

  return (
    <Element
      title={title}
      className={className}
      style={style}
      role="img"
      aria-label={title || icon || ""}
      {...otherAttr}
    />
  );
};

export { EditorIcon, editorIconDefinitions };
